version: '3.1'

services:
  cleanarchmvc-api:
    image: cleanarchmvc-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7143:7143"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - cleanarchmvc-network

networks:
  cleanarchmvc-network:
    driver: bridge
